### ISSUE TITLE
Import issues from GitLab

### ISSUE THREAD

**Issue by dspinellis** [dspinellis/git-issue#41]

**Comment by vyrondrosos** [comment]
In the process of writing my GSoC proposal, I've been considering the consequences of implementing _GitLab_ support.(please let me know if this is not an appropriate place for this discussion)

The main issue I'm seeing, is that _Gitlab_ issues have some attributes that `git-issue` doesn't. Those include due dates, weights(which are only available in the non-free version), time estimates etc. The way I see it, there are 3 ways to rectify this:

* Just ignore the unsupported attributes. This would of course mean that importing and re-exporting an issue wouldn't preserve it, which certainly isn't ideal.
* Add those attributes to `git-issue`. This isn't ideal either, since a) they aren't necessarily useful and b) That would create problems when exporting to _GitHub_, which doesn't have those attributes.
* Represent them using existing attributes. e.g the due date could be appended to the description in text format. This seems sensible to me, except it could create clutter when many such attributes exist.

I'd like to hear your ideas on that matter. Maybe a combination of the above could be implemented, e.g there could be an option to ignore unwanted attributes, or store them.

**Comment by dspinellis** [comment]
I think we should support them (they might be useful), and for every attribute list on which platforms it is supported.  When exporting to a platform that doesn't support some attributes these should be exported as text.

**Comment by dspinellis** [comment]
Implemented by @vyrondrosos as part of GSoC 2019.
